name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: my-web-app
  ECS_SERVICE: my-web-service
  ECS_CLUSTER: my-web-cluster
  ECS_TASK_DEFINITION: ecs-task-definition.json
  CONTAINER_NAME: my-web-container

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Cache Docker layers
      uses: docker/cache-action@v2
      with:
        path: /tmp/.buildx-cache
      
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/$ECR_REPOSITORY:latest .

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/$ECR_REPOSITORY:latest
      
    - name: Fill in the new image ID in the Amazon ECS task definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ secrets.ECR_REGISTRY }}/$ECR_REPOSITORY:latest

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
        aws-region: ${{ env.AWS_REGION }}
